### PR TITLE
german locale revision

### PR DESCRIPTION
**Pull request by emphasize**
Initial changes:
* review translation

dependent on #19 (value change)

### CODE REVIEW

**Comment by emphasize** [comment]
latest commit changed the `langdefault` since it tests for `self.lang` (corrected for it and es as well)

**Comment by emphasize** [comment]
pls wait with the merger as i adress said `is_default` issue alongside

**Comment by emphasize** [comment]
changes:
* langs are now defined with the full lang code
* default feeds are now set for every language. Ie. if one issues a feed from a foreign language (and no feed name/alias is uttered) the default is taken.

**Comment by JarbasAl** [comment]
one more rebase please

**Comment by emphasize** [comment]
vscode can kiss my ass 🥇

**Comment by emphasize** [comment]
closed in favor of #22 , #23

**Pull request closed without merging**
